name: "[User Story] template"
description: "This template aims to create user stories."
title: "Report here what needs to be done"
labels: story

assignees:
  - leafarRafael-Dev

body:
  - type: input
    id: description
    attributes:
      label: "Objectively, what should be done?"
      description: "Ex: Automate software installation flow; Create ssl for https connection;"
      placeholder: ""

  - type: textarea
    id: description
    attributes:
      label: "Give a brief description of the problem: "
      description: "Ex: As a developer, I would like automation X"
      placeholder: ""

  - type: textarea
    id: description
    attributes:
      label: "Objectively, how would this solve the problem?"
      description: "Ex: As a developer, I would like automation X"
      placeholder: 
        value: |
          Ex: Ensures that the environment is configured with the correct dependencies; Increases security between the client and the service.


  - type: textarea
    id: related-issues
    attributes:
      label: "Related Task/Issues"
      description: "List all task/issues related to this story"
      placeholder: "- [ ] #123 Create VPC\n- [ ] #124 Configure CI/CD"

  - type: textarea
    attributes:
      label: "Define EPIC acceptance criteria"
      description: "Type as per the example to create checkboxes"
      placeholder: "- [ ] Item 1\n- [ ] Item 2\n- [ ] Item 3"