name: "[Task/Feature]"
description: "This template is intended for creating tasks."
title: "Ex. Create functionality 'X' in project 'N'; Configure ssl for https protocol;"
labes: task

body:
  - type: textarea
    id: description
    attribute:
      label: context
      