name: "[Task/Feature]"
description: "This template is intended for creating tasks."
title: "Ex. Creating a Dockerfile with nginx software; configuring ssl for https connections;"
labels: task

body:
  - type: input
    attributes:
      label: "Task to be performed"
      description: |
        Ex. Create install command in Makefile

  - type: textarea
    attributes:
      label: "Describe the details of this task."
      placeholder: |
        Example:
        Docker software installation automation;
        Expected version 1.2.3;
        You should check if the software is already installed;

  - type: dropdown
    attributes:
      label: "Priority"
      options:
      - high
      - medium
      - low

  - type: textarea
    attributes:
      label: "Acceptance criteria"
      placeholder: |
        - [ ] Checks first if it was already installed.
        - [ ] Installs from trusted sources.
        - [ ] Assigns the necessary permissions